### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by sibeliusseraphini** [mcgill-cpslab/MonkeyHelper#12]
print without parenthesis is not supported on Python3

**Comment by mingyuan-xia** [comment]
will fix print for python3.
As some components require monkeyrunner, which is bundled with jypthon 2.xx (something even <2.6). So we might not be able to completely switch to python 3. FYI.
Let me know anything else we need to fix to support Python3

**Comment by mingyuan-xia** [comment]
fixed 8d4d40dd093fb7ecfb7d948005f199cb17264293
note that androidviewclient and monkeyrunner-related scripts are still python2.7 only
